### ISSUE TITLE
Problem with two deferred tasks

### ISSUE THREAD

**Issue by sreenath4a1** [nradulovic/neon-eds#4]
As project design, I need to execute one task for every 66 micro sec and the other for very 100 milli sec.
And so both tasks added to deferred scheduler.

Issue:
When system starts both tasks started executing as expected, But certain period of time(random), one task 
100 milli sec task stops executing.

**Comment by nradulovic** [comment]
Hello,

Regarding the error: please, provide more information about the used system and platform:
1. On which MCU is the code running (exact manufacturer part number)?
2. Which compiler is being used (including the version, or git revision if built from source)?
3. Which flash loader is being used and what debug server (Segger JLink, a JTAG...)?
4. Which debugger is being used?
5. How does the error manifest itself? Only through debug? Or you can catch with some external equipment, like oscilloscope...
6. Does the firmware crashes? (some fault handler is fired up?)
7. What other interrupts are enabled and/or running?
8. Code snippet that sets up the deferred task?
9. Please, copy-paste Neon EDS configuration file (.h file)

Also, 66 micro seconds might be too small period for a certain task. It really depends on the task execution time. Did you measured the execution time of the 66 micro sec task?

**Comment by sreenath4a1** [comment]
On which MCU is the code running (exact manufacturer part number)? STM32F411VE
Which compiler is being used (including the version, or git revision if built from source)? latest Git code
Which flash loader is being used and what debug server (Segger JLink, a JTAG...)? JTAG
Does the firmware crashes? (some fault handler is fired up?) NO
What other interrupts are enabled and/or running? (i2c/spi/uart with high priorties)
Code snippet that sets up the deferred task? PFA
[66microsec_Task.txt](https://github.com/nradulovic/neon-eds/files/1922611/66microsec_Task.txt)
[100millisec_Task.txt](https://github.com/nradulovic/neon-eds/files/1922612/100millisec_Task.txt)


Did you measured the execution time of the 66 micro sec task?This task executes with in 30 microsec

****** Always 100 millisecond task stops executing ********
It comes into the below  function and can't enter into ndlist_add_after(); 
void nsched_deferred_do(struct nsched_deferred * deferred)
{
    NREQUIRE(NAPI_POINTER, deferred != NULL);
    NREQUIRE(NAPI_OBJECT, deferred->signature = NSIGNATURE_DEFER);

    if (ndlist_is_empty(&deferred->list)) {
    	ndlist_add_after(g_ctx.pending, &deferred->list);
    }
    ncore_deferred_do();
}

**Comment by nradulovic** [comment]
Hi,

The code snippets seems OK to me. 

When you say "can't enter into ndlist_add_after()" you mean that the if condition "ndlist_is_empty(&deferred->list)" is never true? If that's the case I begin to suspect that the linked list is not consistent. Since list operations are not atomic the list can become inconsistent when a list operation (add, remove..) is interrupted by a higher priority execution context (an ISR) and modifies the list in between the list operation. This may happen if ISR priorities are not configured properly to prevent this. May you post the contents of neon_eds_app_config.h file. We need to check the assigned ISR priorities.

**Comment by sreenath4a1** [comment]
yes ndlist_is_empty(&deferred->list)" is never true...

/*
 * --  IRQ Priorities  --------------------------------------------------------
 *
 * NOTE:
 * Zero level priority is the highest IRQ priority.
 */

#define IRQ_PRIO_TRIGGER_IN             1
#define HWCON_IRQ_PRIO_PROBE_SPI            0
#define HWCON_IRQ_PRIO_PROBE_EXTI           1
#define IRQ_PRIO_TRIGGER_OUT_TIM        2
#define HWCON_IRQ_PRIO_SYSTICK              4
#define HWCON_IRQ_PRIO_NEON                 4
#define HWCON_IRQ_PRIO_AUX_SPI              4
#define HWCON_IRQ_PRIO_AUX_EXTI             5
#define HWCON_IRQ_PRIO_RTCOMM_SPI_DMA_TX    6
#define HWCON_IRQ_PRIO_CTRL                 8
#define HWCON_TEST_TIMER0_IRQ_PRIO      1

//// RTOS task priorities
#define EPA_RTCOMM_PRIO                 31
#define EPA_RTCOMM_QUEUE_SIZE           10
#define EPA_RTCOMM_EVENT_BASE           1000

#define EPA_TRIGGER_PRIO                30
#define EPA_TRIGGER_QUEUE_SIZE          10
#define EPA_TRIGGER_EVENT_BASE          6000

#define EPA_CTRL_PRIO                   29
#define EPA_CTRL_QUEUE_SIZE             10
#define EPA_CTRL_EVENT_BASE             2000

#define EPA_CONTROLLER_PRIO             28
#define EPA_CONTROLLER_QUEUE_SIZE       10
#define EPA_CONTROLLER_EVENT_BASE       3000

**Comment by sreenath4a1** [comment]
Note:
RTOS tasks: 
EPA_RTCOMM,EPA_TRIGGER -> defined as deferred tasks
EPA_CTRL,EPA_CONTROLLER -> defined as timed tasks (normal tasks)
